version: 2.1
executors:
  node:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.12-browsers
jobs:
  build:
    executor:
      name: node
    steps:
      - checkout
      - run:
          name: update-yarn
          command: "sudo yarn add -g yarn@latest"
      - restore_cache: 
          key: node-{{ .Branch }}-{{ checksum "yarn.lock" }}
          # paths:
          # - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: 
          name: build flat
          command: yarn run build
# workflows:
  #  version: 2
  # build-and-cache:
   # jobs:
   #   -build


      # 参照：https://qiita.com/Gma_Gama/items/9df765e00d7fda733222