version: 2.1
jobs:
  install_yarn:
    docker:
      - image: circleci/node
  steps:
    - checkout
    - run: yarn install
    - run: yarn run build
workflows:
  version: 2.1
  run_install:
    jobs:
      - install_yarn
