version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: 
          name: 'this is test of circleCI'
          command: echo 'This is test matcha'

